const atoms = [{"el":"Fe","x":-1.46,"y":-1.46,"z":-1.46},{"el":"Cr","x":0.0,"y":0.0,"z":0.0},{"el":"Ni","x":-1.46,"y":-1.46,"z":1.46},{"el":"Cr","x":0.0,"y":0.0,"z":2.92},{"el":"Cr","x":-1.46,"y":1.46,"z":-1.46},{"el":"Ni","x":0.0,"y":2.92,"z":0.0},{"el":"Cr","x":-1.46,"y":1.46,"z":1.46},{"el":"Ni","x":0.0,"y":2.92,"z":2.92},{"el":"Ni","x":1.46,"y":-1.46,"z":-1.46},{"el":"Cr","x":2.92,"y":0.0,"z":0.0},{"el":"Cr","x":1.46,"y":-1.46,"z":1.46},{"el":"Ni","x":2.92,"y":0.0,"z":2.92},{"el":"Ni","x":1.46,"y":1.46,"z":-1.46},{"el":"Cr","x":2.92,"y":2.92,"z":0.0},{"el":"Cr","x":1.46,"y":1.46,"z":1.46},{"el":"Fe","x":2.92,"y":2.92,"z":2.92}];
const colors={Fe:['#d9e0e8','#8994a1'],Ni:['#9ec3ff','#446ea9'],Cr:['#9ff2d3','#367c68']};
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),tip=document.getElementById('tooltip');
let W=0,H=0,dpr=1,rx=-.52,ry=.67,zoom=1,spin=true,mode=0,drag=false,lastX=0,lastY=0,projected=[];
const a=2.92,cell=2*a,center=cell/2-a/2;
const cube=[[-a/2,-a/2,-a/2],[cell-a/2,-a/2,-a/2],[cell-a/2,cell-a/2,-a/2],[-a/2,cell-a/2,-a/2],[-a/2,-a/2,cell-a/2],[cell-a/2,-a/2,cell-a/2],[cell-a/2,cell-a/2,cell-a/2],[-a/2,cell-a/2,cell-a/2]].map(([x,y,z])=>({x:x-center,y:y-center,z:z-center}));
const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];
const bonds=[];for(let i=0;i<atoms.length;i++)for(let j=i+1;j<atoms.length;j++){let p=atoms[i],q=atoms[j],d=Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z);if(d<2.60)bonds.push([i,j]);}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}
function rotate(p){let cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx);let x=p.x*cy+p.z*sy,z=-p.x*sy+p.z*cy,y=p.y;return{x,y:y*cx-z*sx,z:y*sx+z*cx};}
function proj(p){let r=rotate(p),s=Math.min(W,H)*.103*zoom,pers=7.5/(7.5+r.z*.22);return{x:W*.49+r.x*s*pers,y:H*.52-r.y*s*pers,z:r.z,scale:pers};}
function line(p,q,color,width=1){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function drawSphere(p,r,c1,c2){let g=ctx.createRadialGradient(p.x-r*.32,p.y-r*.36,r*.08,p.x,p.y,r);g.addColorStop(0,'#ffffff');g.addColorStop(.13,c1);g.addColorStop(1,c2);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=g;ctx.shadowColor='rgba(0,0,0,.50)';ctx.shadowBlur=16;ctx.shadowOffsetY=6;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=.7;ctx.stroke();}
function render(){ctx.clearRect(0,0,W,H);let glow=ctx.createRadialGradient(W*.5,H*.53,20,W*.5,H*.53,Math.min(W,H)*.52);glow.addColorStop(0,'rgba(77,145,255,.07)');glow.addColorStop(.5,'rgba(80,255,190,.025)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);const cp=cube.map(proj);edges.forEach(([i,j])=>line(cp[i],cp[j],'rgba(173,198,226,.18)',1));projected=atoms.map((p,i)=>({...proj(p),i,el:p.el}));if(mode!==2){for(const [i,j] of bonds){let p=projected[i],q=projected[j];line(p,q,mode===0?'rgba(189,207,224,.22)':'rgba(189,207,224,.10)',mode===0?2.2:1)}}if(mode!==2){[...projected].sort((a,b)=>a.z-b.z).forEach(p=>{let rad=(mode===1?16:12)*p.scale*zoom*.94;drawSphere(p,rad,...colors[p.el]);});}else{[...projected].sort((a,b)=>a.z-b.z).forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,3.3,0,Math.PI*2);ctx.fillStyle=colors[p.el][0];ctx.fill();});}}
function frame(){if(spin&&!drag)ry+=.0025;render();requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){ry+=(e.clientX-lastX)*.008;rx+=(e.clientY-lastY)*.008;lastX=e.clientX;lastY=e.clientY;tip.style.display='none';return}let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,best=null,dist=28;for(const p of projected){let d=Math.hypot(p.x-x,p.y-y);if(d<dist){best=p;dist=d}}if(best){let atom=atoms[best.i];tip.innerHTML=`<strong>${best.el} · atom ${String(best.i+1).padStart(2,'0')}</strong>x ${atom.x.toFixed(3)} · y ${atom.y.toFixed(3)} · z ${atom.z.toFixed(3)} Å`;tip.style.display='block';tip.style.left=Math.min(W-185,x+16)+'px';tip.style.top=Math.min(H-85,y+16)+'px'}else tip.style.display='none'});canvas.addEventListener('pointerup',e=>{drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('mouseleave',()=>tip.style.display='none');canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(1.55,zoom*(e.deltaY>0?.92:1.08))) },{passive:false});
document.getElementById('spinBtn').onclick=function(){spin=!spin;this.classList.toggle('active',spin);this.textContent=spin?'Auto rotate':'Rotation paused'};
document.getElementById('resetBtn').onclick=()=>{rx=-.52;ry=.67;zoom=1};document.getElementById('modeBtn').onclick=function(){mode=(mode+1)%3;this.textContent=['Ball + stick','Atoms only','Wireframe'][mode]};
new ResizeObserver(resize).observe(canvas);resize();frame();
