const REPLAY_MODE=new URLSearchParams(location.search).get('replay')==='1';
const VIEWER_BUILD='material-evidence-card/v0.0.7-p0+replay.2';
const REPLAY_CONTRACT='SEMANTIC_VIEW_RECREATION_NOT_PIXEL_IDENTITY';
const INITIAL_VIEW=Object.freeze({preset:'INITIAL_ISOMETRIC',rx:-.52,ry:.67,zoom:1,mode:0,representation:'BALL_AND_STICK'});
const BOND_CUTOFF=2.62;
const REPLAY_LAYOUT_TOLERANCE_DEVICE_PX=.5;
let replayStatus=REPLAY_MODE?'BOOTING':'DISABLED',replayReceipt=null,replayError=null;
Object.defineProperty(globalThis,'__mecReplayReady',{configurable:false,get:()=>replayStatus==='READY'});
Object.defineProperty(globalThis,'__MEC_REPLAY__',{configurable:false,writable:false,value:Object.freeze({api_version:'1.0',get status(){return replayStatus},get ready(){return replayStatus==='READY'},getReceipt(){return replayReceipt?structuredClone(replayReceipt):null},getError(){return replayError?structuredClone(replayError):null}})});

const atoms = [{"el":"Fe","x":-1.47,"y":-1.47,"z":-1.47},{"el":"Cr","x":0.0,"y":0.0,"z":0.0},{"el":"Fe","x":-1.47,"y":-1.47,"z":1.47},{"el":"Cr","x":0.0,"y":0.0,"z":2.94},{"el":"Cr","x":-1.47,"y":1.47,"z":-1.47},{"el":"Fe","x":0.0,"y":2.94,"z":0.0},{"el":"Cr","x":-1.47,"y":1.47,"z":1.47},{"el":"Ni","x":0.0,"y":2.94,"z":2.94},{"el":"Fe","x":1.47,"y":-1.47,"z":-1.47},{"el":"Cr","x":2.94,"y":0.0,"z":0.0},{"el":"Cr","x":1.47,"y":-1.47,"z":1.47},{"el":"Fe","x":2.94,"y":0.0,"z":2.94},{"el":"Ni","x":1.47,"y":1.47,"z":-1.47},{"el":"Cr","x":2.94,"y":2.94,"z":0.0},{"el":"Cr","x":1.47,"y":1.47,"z":1.47},{"el":"Fe","x":2.94,"y":2.94,"z":2.94}];
const colors={Fe:['#d9e0e8','#8994a1'],Ni:['#9ec3ff','#446ea9'],Cr:['#9ff2d3','#367c68']};
const canvas=document.getElementById('stage'),ctx=canvas.getContext('2d'),tip=document.getElementById('tooltip');
if(!ctx){publishReplayError('CANVAS_2D_UNAVAILABLE',new Error('Canvas 2D context is unavailable'));throw new Error('CANVAS_2D_UNAVAILABLE')}
let W=0,H=0,dpr=1,rx=INITIAL_VIEW.rx,ry=INITIAL_VIEW.ry,zoom=INITIAL_VIEW.zoom,spin=!REPLAY_MODE,mode=INITIAL_VIEW.mode,drag=false,lastX=0,lastY=0,projected=[],lastRenderMetrics=null;
const a=2.94,cell=2*a,center=cell/2-a/2;
const cube=[[-a/2,-a/2,-a/2],[cell-a/2,-a/2,-a/2],[cell-a/2,cell-a/2,-a/2],[-a/2,cell-a/2,-a/2],[-a/2,-a/2,cell-a/2],[cell-a/2,-a/2,cell-a/2],[cell-a/2,cell-a/2,cell-a/2],[-a/2,cell-a/2,cell-a/2]].map(([x,y,z])=>({x:x-center,y:y-center,z:z-center}));
const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];
const bonds=[];for(let i=0;i<atoms.length;i++)for(let j=i+1;j<atoms.length;j++){let p=atoms[i],q=atoms[j],d=Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z);if(d<BOND_CUTOFF)bonds.push([i,j]);}
function measureCanvas(){const r=canvas.getBoundingClientRect(),nextDpr=REPLAY_MODE?1:Math.min(devicePixelRatio||1,2);return{width:r.width,height:r.height,dpr:nextDpr,pixelWidth:Math.round(r.width*nextDpr),pixelHeight:Math.round(r.height*nextDpr)}}
function resize(measurement=measureCanvas()){const changed=canvas.width!==measurement.pixelWidth||canvas.height!==measurement.pixelHeight;dpr=measurement.dpr;W=measurement.width;H=measurement.height;if(changed){canvas.width=measurement.pixelWidth;canvas.height=measurement.pixelHeight}ctx.setTransform(dpr,0,0,dpr,0,0);return changed;}
function replayLayoutChanged(measurement){const baseline=replayReceipt?.canvas_observation;if(!baseline)return true;const cssTolerance=REPLAY_LAYOUT_TOLERANCE_DEVICE_PX/baseline.dpr;return canvas.width!==baseline.pixel_width||canvas.height!==baseline.pixel_height||measurement.pixelWidth!==baseline.pixel_width||measurement.pixelHeight!==baseline.pixel_height||Math.abs(measurement.dpr-baseline.dpr)>1e-12||Math.abs(measurement.width-baseline.css_width)>cssTolerance||Math.abs(measurement.height-baseline.css_height)>cssTolerance}
function rotate(p){let cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx);let x=p.x*cy+p.z*sy,z=-p.x*sy+p.z*cy,y=p.y;return{x,y:y*cx-z*sx,z:y*sx+z*cx};}
function proj(p){let r=rotate(p),s=Math.min(W,H)*.103*zoom,pers=7.5/(7.5+r.z*.22);return{x:W*.49+r.x*s*pers,y:H*.52-r.y*s*pers,z:r.z,scale:pers};}
function line(p,q,color,width=1){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function drawSphere(p,r,c1,c2){let g=ctx.createRadialGradient(p.x-r*.32,p.y-r*.36,r*.08,p.x,p.y,r);g.addColorStop(0,'#ffffff');g.addColorStop(.13,c1);g.addColorStop(1,c2);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=g;ctx.shadowColor='rgba(0,0,0,.50)';ctx.shadowBlur=16;ctx.shadowOffsetY=6;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=.7;ctx.stroke();}
function render(){ctx.clearRect(0,0,W,H);let glow=ctx.createRadialGradient(W*.5,H*.53,20,W*.5,H*.53,Math.min(W,H)*.52);glow.addColorStop(0,'rgba(77,145,255,.07)');glow.addColorStop(.5,'rgba(80,255,190,.025)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);const cp=cube.map(proj);edges.forEach(([i,j])=>line(cp[i],cp[j],'rgba(173,198,226,.18)',1));projected=atoms.map((p,i)=>({...proj(p),i,el:p.el}));if(mode!==2){for(const [i,j] of bonds){let p=projected[i],q=projected[j];line(p,q,mode===0?'rgba(189,207,224,.22)':'rgba(189,207,224,.10)',mode===0?2.2:1)}}if(mode!==2){[...projected].sort((a,b)=>a.z-b.z).forEach(p=>{let rad=(mode===1?16:12)*p.scale*zoom*.94;drawSphere(p,rad,...colors[p.el]);});}else{[...projected].sort((a,b)=>a.z-b.z).forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,3.3,0,Math.PI*2);ctx.fillStyle=colors[p.el][0];ctx.fill();});}lastRenderMetrics={atom_draw_count:projected.length,bond_draw_count:mode===2?0:bonds.length,bounds_edge_draw_count:edges.length};return lastRenderMetrics;}
function frame(){if(spin&&!drag)ry+=.0025;render();requestAnimationFrame(frame)}

function publishReplayError(code,error){replayReceipt=null;replayStatus='ERROR';replayError={code,message:error instanceof Error?error.message:String(error)};document.documentElement.dataset.renderReplay='error';globalThis.dispatchEvent(new CustomEvent('mec-render-error',{detail:structuredClone(replayError)}));}
function buildReplayReceipt(){const elementCounts=atoms.reduce((counts,atom)=>{counts[atom.el]=(counts[atom.el]||0)+1;return counts},{});return Object.freeze({receipt_schema:'MEC_PAGE_OBSERVATION_V1',observation_status:'READY',replay_contract:REPLAY_CONTRACT,viewer_build:VIEWER_BUILD,source_mode:'EMBEDDED_COORDINATES',runtime_structure_hash_verified:false,transformation:'FIXED_TRANSLATION_ONLY',camera:{preset:INITIAL_VIEW.preset,rx,ry,zoom},representation:INITIAL_VIEW.representation,mode,spin,animation_loop:false,post_ready_layout_guard:{max_css_drift_device_px:REPLAY_LAYOUT_TOLERANCE_DEVICE_PX,backing_store_must_match:true,dpr_must_match:true},atom_count:atoms.length,element_counts:elementCounts,ordered_atoms:atoms.map(({el,x,y,z})=>({el,x,y,z})),bond_cutoff:BOND_CUTOFF,bond_pairs:bonds.map(pair=>[...pair]),draw_counts:{...lastRenderMetrics},projected_atoms:projected.map(({i,el,x,y,z,scale})=>({index:i,el,x,y,z,scale})),canvas_observation:{css_width:W,css_height:H,pixel_width:canvas.width,pixel_height:canvas.height,dpr}})}
function publishReplayReady(){replayReceipt=buildReplayReceipt();replayStatus='READY';document.documentElement.dataset.renderReplay='ready';globalThis.dispatchEvent(new CustomEvent('mec-render-ready',{detail:{viewer_build:VIEWER_BUILD}}));}
function startDeterministicReplay(){spin=false;mode=INITIAL_VIEW.mode;rx=INITIAL_VIEW.rx;ry=INITIAL_VIEW.ry;zoom=INITIAL_VIEW.zoom;canvas.style.pointerEvents='none';const spinButton=document.getElementById('spinBtn');spinButton.classList.remove('active');spinButton.textContent='Replay view locked';document.querySelectorAll('.controls button').forEach(button=>{button.disabled=true});replayStatus='WAITING_FOR_LAYOUT';let previous='',stableFrames=0,attempts=0;function settle(){try{attempts+=1;resize();const signature=`${W.toFixed(3)}x${H.toFixed(3)}@${dpr}`;if(W>0&&H>0&&signature===previous)stableFrames+=1;else stableFrames=0;previous=signature;if(stableFrames>=2){replayStatus='RENDERING';render();publishReplayReady();return}if(attempts>=8){publishReplayError('LAYOUT_INVALID',new Error(`Canvas layout did not stabilize: ${signature}`));return}requestAnimationFrame(settle)}catch(error){publishReplayError('RENDER_EXCEPTION',error)}}requestAnimationFrame(settle)}
canvas.addEventListener('pointerdown',e=>{if(REPLAY_MODE)return;drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(REPLAY_MODE)return;if(drag){ry+=(e.clientX-lastX)*.008;rx+=(e.clientY-lastY)*.008;lastX=e.clientX;lastY=e.clientY;tip.style.display='none';return}let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,best=null,dist=28;for(const p of projected){let d=Math.hypot(p.x-x,p.y-y);if(d<dist){best=p;dist=d}}if(best){let atom=atoms[best.i];tip.innerHTML=`<strong>${best.el} · atom ${String(best.i+1).padStart(2,'0')}</strong>x ${atom.x.toFixed(3)} · y ${atom.y.toFixed(3)} · z ${atom.z.toFixed(3)} Å`;tip.style.display='block';tip.style.left=Math.min(W-185,x+16)+'px';tip.style.top=Math.min(H-85,y+16)+'px'}else tip.style.display='none'});canvas.addEventListener('pointerup',e=>{if(REPLAY_MODE)return;drag=false;canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointercancel',()=>{if(REPLAY_MODE)return;drag=false});canvas.addEventListener('mouseleave',()=>{if(REPLAY_MODE)return;tip.style.display='none'});canvas.addEventListener('wheel',e=>{if(REPLAY_MODE)return;e.preventDefault();zoom=Math.max(.65,Math.min(1.55,zoom*(e.deltaY>0?.92:1.08))) },{passive:false});
document.getElementById('spinBtn').onclick=function(){if(REPLAY_MODE)return;spin=!spin;this.classList.toggle('active',spin);this.textContent=spin?'Auto rotate':'Rotation paused'};
document.getElementById('resetBtn').onclick=()=>{if(REPLAY_MODE)return;rx=INITIAL_VIEW.rx;ry=INITIAL_VIEW.ry;zoom=INITIAL_VIEW.zoom};document.getElementById('modeBtn').onclick=function(){if(REPLAY_MODE)return;mode=(mode+1)%3;this.textContent=['Ball + stick','Atoms only','Wireframe'][mode]};
new ResizeObserver(()=>{const measurement=measureCanvas();if(REPLAY_MODE&&replayStatus==='READY'){if(replayLayoutChanged(measurement)){const baseline=replayReceipt.canvas_observation;publishReplayError('LAYOUT_CHANGED_AFTER_READY',new Error(`Canvas layout changed after READY: baseline=${baseline.css_width}x${baseline.css_height}@${baseline.dpr}, observed=${measurement.width}x${measurement.height}@${measurement.dpr}`))}return}resize(measurement)}).observe(canvas);resize();if(REPLAY_MODE)startDeterministicReplay();else frame();
